# Generated by Django 5.2.1 on 2025-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellido"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Fecha de Nacimiento")),
                ("address", models.CharField(max_length=255, verbose_name="Dirección")),
                ("city", models.CharField(max_length=100, verbose_name="Ciudad")),
                ("state", models.CharField(max_length=100, verbose_name="Estado")),
                (
                    "zip_code",
                    models.CharField(max_length=20, verbose_name="Código Postal"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Número de Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo Electrónico"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "joined_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Ingreso"
                    ),
                ),
            ],
        ),
    ]
